[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#000000"

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Retina"

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[font.offset]
x = 0
y = 1

[scrolling]
history = 5000

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "none"
opacity = 3

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 10
y = 10

[terminal]
